export const YOUTUBE_FETCHER = 'YOUTUBE_FETCHER';
export const YOUTUBE_SONG = 'YOUTUBE_SONG';

export const STATE_DOWNLOADED = 'STATE_DOWNLOADED';
export const STATE_DOWNLOADING = 'STATE_DOWNLOADING';